### PR TITLE
# Feature/qg 22 enable quiz download in preferred format in the backend

### PR DESCRIPTION
**Pull request by IAmFocus90**
# Pull Request: Add Download Feature for Quiz Data

## Description
This pull request introduces a feature that allows users to download quiz data in various file formats: `.txt`, `.csv`, `.pdf`, and `.docx`. The implementation adheres to industry best practices for both frontend and backend development, ensuring scalability and reliability.

---

## Key Features
- **Supported File Formats:** `.txt`, `.csv`, `.pdf`, `.docx`.
- **Backend Integration:**
  - Implements file generation and download-quiz logic using FastAPI.
  - Streams generated files directly to the frontend for downloading.
- **Frontend Enhancements:**
  - Seamless integration of the download feature within the UI.
  - Conditional rendering for managing file format selection.
  - Utilizes **RxJS Observables** for handling the download stream, ensuring smooth and reactive handling of file data as it is received.

---

## Changes Made
- Added a new API endpoint in the backend for file generation.
- Added a new API endpoint in the backend for quiz-download and streaming.
- Refactored the download functionality to move file creation logic to the server.
- Updated frontend components to enhance usability and maintain design consistency.
- Integrated RxJS Observables in the frontend to handle file download streams efficiently.

---

## Dependencies Added
- **Frontend:**
  - **Axios:** Used for making HTTP requests to the backend API.
  - **RxJS:** Used for reactive programming, especially handling asynchronous operations like receiving the download streams.

- **Backend:**
  - **ReportLab:** Used to generate PDF files from quiz data.
  - **python-docx:** Used to generate `.docx` files from quiz data.

---

## Testing
- Verified that downloads work correctly for all supported file formats.
- Ensured error handling is robust for unsupported file types or failed download attempts.
- Tested for compatibility across major browsers.

---

## How to Test
1. On the landing page select a Quiz Type from the dropdown menu.
2. Scroll to the end of the displayed generated quiz and choose the desired file format for downloading.
3. Click the **Download** button to retrieve the quiz data in the chosen format.

### CODE REVIEW

**Comment by IAmFocus90** [comment]
The conflict with master branch have been resolved

**Comment by Glorycornel** [comment]
I've reviewed and everything works as it should, however there's a minor conflict that needs to be resolved before it can be merged. Hoping  we resolve this on Friday.
Screenshot from 2024-11-20 09-37-10
Screenshot from 2024-11-20 09-36-41

**Review by julietowah — APPROVED** [review]

**Comment by julietowah** [comment]
Please can you add more details on how the feature like steps to the feature so i can test it

**Comment by IAmFocus90** [comment]
@julietowah  follow the same procedure as explained in the Pull Requests's HOW TO TEST to confirm that the download functionality is still effective. your confirmation is necessary because this download feature is now integrated into the apps quiz-display page

**Review by Glorycornel — APPROVED** [review]

**Pull request merged**
